name: 'Fetch Helm Chart'
description: 'Pull and Export helm chart'

inputs:
  chart:
    description: 'Chart to fetch'
    required: true
  version:
    description: 'Version of Chart to fetch'
    required: true
  exportPath:
    description: 'Path to export chart to'
    required: true
    default: .helm/charts/
  registryUrl: 
    description: "ECR Registry URL"
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        HELM_CHART: ${{ inputs.chart }}
        VERSION: ${{ inputs.version }}
        ECR_ENDPOINT: ${{ inputs.registryUrl }}
        EXPORT_PATH: ${{ inputs.exportPath }}
      run: |
        # helm 3.7.0
        # https://github.com/actions/virtual-environments/pull/4110
        # https://github.com/helm/helm/issues/10122#issuecomment-922900257
        export HELM_EXPERIMENTAL_OCI=1
        aws ecr get-login-password | helm registry login --username AWS --password-stdin ${ECR_ENDPOINT}
        helm pull oci://${ECR_ENDPOINT}/charts/${HELM_CHART} --version ${VERSION}
        mkdir -p ${EXPORT_PATH} && tar -zxvf "${HELM_CHART}-${VERSION}.tgz" -C ${EXPORT_PATH}
